Repository inf112-v20/biblioteket, pull requests merged in 2020-02, with the labels that each got.

#6 Add CI, upgrade package versions, minor scaffolding
  .github/workflows/pipeline.yml
  .gitignore
  README.md
  default.nix
  pom.xml
  src/test/java/inf112/skeleton/app/AppTest.java
Labels: enhancement

#14 Fix `mvn -B package` jar referencing wrong class
  README.md
  pom.xml
Labels: bug

#17 Delivered assignment
  deliverables/ObligatoriskOppgave1.md
  deliverables/UML.png
Labels: documentation

#16 Intial pass at testing
  pom.xml
  src/main/java/biblioteket/roborally/Game.java
  src/test/java/biblioteket/roborally/AppTest.java
  src/test/java/biblioteket/roborally/GameTest.java
Labels: enhancement

#18 Assignment 1
  .github/workflows/pipeline.yml
  .gitignore
  README.md
  assets/board.tmx
  assets/player.png
  assets/tiles.tsx
  default.nix
  deliverables/ObligatoriskOppgave1.md
  deliverables/UML.png
  pom.xml
  src/main/java/biblioteket/roborally/Game.java
  src/main/java/biblioteket/roborally/Main.java
  src/main/java/inf112/skeleton/app/HelloWorld.java
  src/main/java/inf112/skeleton/app/Main.java
  src/test/java/biblioteket/roborally/AppTest.java
  src/test/java/biblioteket/roborally/GameTest.java
  src/test/java/inf112/skeleton/app/AppTest.java
Labels: epic

#27 Added locations and directions
  src/main/java/biblioteket/roborally/BoardDirections.java
  src/main/java/biblioteket/roborally/ILocation.java
  src/main/java/biblioteket/roborally/Location.java
  src/test/java/biblioteket/roborally/BoardDirectionsTest.java
  src/test/java/biblioteket/roborally/LocationTest.java
Labels: enhancement

#35 Deliverable 2
  deliverables/ObligatoriskOppgave2.md
Labels: documentation

#34 Grid and Gameboard
  src/main/java/biblioteket/roborally/Direction.java
  src/main/java/biblioteket/roborally/GameBoard.java
  src/main/java/biblioteket/roborally/IElement.java
  src/main/java/biblioteket/roborally/IGameBoard.java
  src/main/java/biblioteket/roborally/actors/IRobot.java
  src/main/java/biblioteket/roborally/actors/ImmovableElement.java
  src/main/java/biblioteket/roborally/actors/Robot.java
  src/main/java/biblioteket/roborally/grid/Grid.java
  src/main/java/biblioteket/roborally/grid/IGrid.java
  src/main/java/biblioteket/roborally/grid/IPosition.java
  src/main/java/biblioteket/roborally/grid/Position.java
  src/test/java/biblioteket/roborally/DirectionTest.java
  src/test/java/biblioteket/roborally/GameBoardTest.java
  src/test/java/biblioteket/roborally/Grid/GridTest.java
  src/test/java/biblioteket/roborally/LocationTest.java
  src/test/java/biblioteket/roborally/actors/RobotTest.java
  src/test/java/biblioteket/roborally/grid/GridTest.java
  src/test/java/biblioteket/roborally/grid/PositionTest.java
Labels: enhancement

#33 Implement main menu and game screen
  src/main/java/biblioteket/roborally/Game.java
  src/main/java/biblioteket/roborally/Main.java
  src/main/java/biblioteket/roborally/game/GameScreen.java
  src/main/java/biblioteket/roborally/game/IGame.java
  src/main/java/biblioteket/roborally/game/MainMenuScreen.java
  src/main/java/biblioteket/roborally/game/RoboRally.java
Labels: enhancement
