Repository inf112-v20/biblioteket, pull requests merged in 2020-05, with the labels that each got.

#125 Priority on programcards, and fixed resizing.
  assets/buttons/arrowLeftPost.png
  assets/buttons/arrowLeftPre.png
  assets/buttons/arrowRightPost.png
  assets/buttons/arrowRightPre.png
  assets/buttons/easyPost.png
  assets/buttons/easyPre.png
  assets/buttons/hardPost.png
  assets/buttons/hardPre.png
  assets/buttons/mainMenuPost.png
  assets/buttons/mainMenuPre.png
  assets/buttons/normalPost.png
  assets/buttons/normalPre.png
  assets/buttons/playPost.png
  assets/buttons/playPre.png
  assets/buttons/quitPost.png
  assets/buttons/quitPre.png
  assets/buttons/selectPost.png
  assets/buttons/selectPre.png
  assets/damageToken.png
  assets/gamemaps/dizzyPost.png
  assets/gamemaps/dizzyPre.png
  assets/gamemaps/riskyPost.png
  assets/gamemaps/riskyPre.png
  assets/numbers/1.png
  assets/numbers/2.png
  assets/numbers/3.png
  assets/numbers/4.png
  assets/numbers/5.png
  assets/numbers/6.png
  assets/numbers/7.png
  assets/numbers/8.png
  assets/numbers/9.png
  assets/selectMap.png
  assets/selectPlayers.png
  src/main/java/biblioteket/roborally/actors/Actor.java
  src/main/java/biblioteket/roborally/actors/InterfaceRenderer.java
  src/main/java/biblioteket/roborally/actors/RobotRenderer.java
  src/main/java/biblioteket/roborally/game/Assets.java
  src/main/java/biblioteket/roborally/game/DifficultySelect.java
  src/main/java/biblioteket/roborally/game/EndGameScreen.java
  src/main/java/biblioteket/roborally/game/GameLoop.java
  src/main/java/biblioteket/roborally/game/GameScreen.java
  src/main/java/biblioteket/roborally/game/IGame.java
  src/main/java/biblioteket/roborally/game/MainMenuScreen.java
  src/main/java/biblioteket/roborally/game/MapSelect.java
  src/main/java/biblioteket/roborally/game/PlayerSelect.java
  src/main/java/biblioteket/roborally/game/StandardScreen.java
  src/test/java/biblioteket/roborally/actors/PlayerTest.java
Labels: enhancement

#143 Powerdown feature
  src/main/java/biblioteket/roborally/actors/Actor.java
  src/main/java/biblioteket/roborally/actors/IActor.java
  src/main/java/biblioteket/roborally/actors/PlayerState.java
  src/main/java/biblioteket/roborally/actors/Robot.java
  src/main/java/biblioteket/roborally/board/Board.java
  src/main/java/biblioteket/roborally/elements/interacting/conveyorbelts/ConveyorBeltElement.java
  src/main/java/biblioteket/roborally/elements/walls/Laser.java
  src/main/java/biblioteket/roborally/game/GameLoop.java
  src/test/java/biblioteket/roborally/actors/PlayerTest.java
Labels: enhancement

#148 Spring cleaning
  .github/workflows/pipeline.yml
  assets/playermodels/owlbot.png
  pom.xml
  src/main/java/biblioteket/roborally/Main.java
  src/main/java/biblioteket/roborally/actors/Actor.java
  src/main/java/biblioteket/roborally/actors/BarrelBot.java
  src/main/java/biblioteket/roborally/actors/EasyAI.java
  src/main/java/biblioteket/roborally/actors/IActor.java
  src/main/java/biblioteket/roborally/actors/INonPlayer.java
  src/main/java/biblioteket/roborally/actors/InterfaceRenderer.java
  src/main/java/biblioteket/roborally/actors/PlayerState.java
  src/main/java/biblioteket/roborally/actors/RobotRenderer.java
  src/main/java/biblioteket/roborally/board/Board.java
  src/main/java/biblioteket/roborally/board/Element.java
  src/main/java/biblioteket/roborally/board/IBoard.java
  src/main/java/biblioteket/roborally/board/MapReader.java
  src/main/java/biblioteket/roborally/elements/interacting/FlagElement.java
  src/main/java/biblioteket/roborally/elements/interacting/SingleWrenchRepairElement.java
  src/main/java/biblioteket/roborally/elements/interacting/conveyorbelts/ExpressConveyorBeltElement.java
  src/main/java/biblioteket/roborally/elements/walls/LaserWallElement.java
  src/main/java/biblioteket/roborally/game/AISelect.java
  src/main/java/biblioteket/roborally/game/AssetLoader.java
  src/main/java/biblioteket/roborally/game/Assets.java
  src/main/java/biblioteket/roborally/game/DifficultySelect.java
  src/main/java/biblioteket/roborally/game/EndGameScreen.java
  src/main/java/biblioteket/roborally/game/GameLoop.java
  src/main/java/biblioteket/roborally/game/GameScreen.java
  src/main/java/biblioteket/roborally/game/PlayerSelect.java
  src/main/java/biblioteket/roborally/game/RoboRally.java
  src/main/java/biblioteket/roborally/game/StandardScreen.java
  src/main/java/biblioteket/roborally/programcards/Card.java
  src/main/java/biblioteket/roborally/programcards/CardDeck.java
  src/test/java/biblioteket/roborally/ManualTests.md
  src/test/java/biblioteket/roborally/actors/PlayerTest.java
  src/test/java/biblioteket/roborally/actors/RobotTest.java
  src/test/java/biblioteket/roborally/elements/interacting/ConveyorBeltTest.java
  src/test/java/biblioteket/roborally/elements/interacting/HoleTest.java
  src/test/java/biblioteket/roborally/programcards/CardDeckTest.java
  src/test/java/biblioteket/roborally/programcards/CardTest.java
Labels: documentation, enhancement, epic

#152 Update javadoc, permissions and remove unused methods, and increase test coverage
  src/main/java/biblioteket/roborally/actors/Actor.java
  src/main/java/biblioteket/roborally/actors/IActor.java
  src/main/java/biblioteket/roborally/actors/InterfaceRenderer.java
  src/main/java/biblioteket/roborally/actors/PlayerState.java
  src/main/java/biblioteket/roborally/actors/RobotRenderer.java
  src/main/java/biblioteket/roborally/board/Board.java
  src/main/java/biblioteket/roborally/board/IBoard.java
  src/main/java/biblioteket/roborally/board/MapReader.java
  src/main/java/biblioteket/roborally/elements/walls/Laser.java
  src/main/java/biblioteket/roborally/game/GameLoop.java
  src/test/java/biblioteket/roborally/actors/PlayerStateTest.java
  src/test/java/biblioteket/roborally/actors/RobotRendererTest.java
  src/test/java/biblioteket/roborally/board/MapReaderTest.java
  src/test/java/biblioteket/roborally/elements/walls/LaserTest.java
  src/test/java/biblioteket/roborally/elements/walls/WallTest.java
Labels: documentation

#153 Assignment 4
  deliverables/ObligatoriskOppgave4.md
  deliverables/milestone4.png
  deliverables/projectboard4.png
  deliverables/uml4-large.png
  deliverables/uml4.png
  src/main/java/biblioteket/roborally/actors/InterfaceRenderer.java
  src/main/java/biblioteket/roborally/actors/RobotRenderer.java
  src/main/java/biblioteket/roborally/game/GameLoop.java
  src/test/java/biblioteket/roborally/ManualTests.md
Labels: documentation
